### ISSUE TITLE
외부 API 요청 및 포매팅 학습

### ISSUE THREAD

**Issue by rookedsysc** [rookedsysc/helloworld#5]
## Overview

외부 API 요청 및 포매팅 학습

## Todo 

- [x] RestClient, ~~WebClient 학습~~ WebClient는 Jetty 의존성이 있기 때문에 추후 학습으로 변경
- [x] JSON 맵핑 방법 조사
- [x] XML 맵핑 방법 조사

## Reference

- [질병 정보 Open API](https://www.data.go.kr/iim/api/selectAPIAcountView.do)

## Issue

- API 호출 코드 작성시 API Key **Encoding된 Key를 사용**해야 함
- 04 HTTP Route Error 발생시 Http Header 적절하게 설정해줘야 함
